server:
  port: 8098

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/silence-platform?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: admin123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: silence_auth_center
      max-lifetime: 1800000

mybatis-plus:
  configuration:
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
    # 日志输出 SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.old.silence.data.commons.handler.GenericEnumTypeHandler
  global-config:
    db-config:
      # 全局主键类型（可选）
      id-type: auto
      # 逻辑删除字段（可选）
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-handlers-package: com.old.silence.data.commons.handler

platform:
  system:
    identifier: AC

