server:
  port: 8096

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
  application.name: auth-service
  messages.basename: messages/silence_auth_center_messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.silence-ci.com:3306/silence-platform?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: silenceopr
    password: -Dv09zr*^ck_7Q6A82
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: silence_auth_center_pool
      max-lifetime: 1800000
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: false
    nacos:
      discovery:
        server-addr: http://www.silence-ci.com:8848
        username: nacos
        password: nacos
  data.redis:
    # 主机
    host: 127.0.0.1
    # 数据库
    database: 0
    # 端口
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis-plus:
  configuration:
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
    # 日志输出 SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.old.silence.data.commons.handler.GenericEnumTypeHandler
  global-config:
    db-config:
      # 全局主键类型（可选）
      id-type: auto
      # 逻辑删除字段（可选）
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-handlers-package: com.old.silence.data.commons.handler

platform:
  system:
    identifier: AC